[workspace]
resolver = "2"
members = ["tgbr-core"]

[package]
name = "tgbr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tgbr-core = { path = "tgbr-core" }
anyhow = "1.0.53"
argopt = "0.3.0"
ciborium = "0.2.0"
directories = "4.0.1"
env_logger = "0.9.0"
log = "0.4.14"
prettytable-rs = "0.8.0"
scopeguard = "1.1.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
tempfile = "3.3.0"
zip = "0.5.13"

bevy = { version = "0.6.1", features = ["serialize"] }
bevy_egui = "0.11.1"
bevy_kira_audio = "0.8.0"
rfd = "0.7.0"

[dev-dependencies]
base64 = "0.13.0"
serde = "1.0.136"
serde-bytes-repr = "0.1.5"
serde_json = "1.0.78"
toml = "0.5.8"
