[workspace]
members = ["tgbr-core"]

[package]
name = "tgbr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tgbr-core = { path = "tgbr-core" }
anyhow = "1.0.53"
argopt = "0.2.0"
ciborium = "0.2.0"
env_logger = "0.9.0"
log = "0.4.14"
prettytable-rs = "0.8.0"
sdl2 = { version = "0.35.2", features = ["ttf"] }
tempfile = "3.3.0"
zip = "0.5.13"

[dev-dependencies]
base64 = "0.13.0"
serde = "1.0.136"
serde-bytes-repr = "0.1.5"
serde_json = "1.0.78"
toml = "0.5.8"
