[package]
name = "tgbr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
argopt = "0.2.0"
bitvec = "1.0.0"
bytesize = "1.1.0"
env_logger = "0.9.0"
log = "0.4.14"
prettytable-rs = "0.8.0"
sdl2 = { version = "0.35.1", features = ["ttf"] }
zip = "0.5.13"
