name: CI

on: [push, pull_request]

jobs:
  x86_64-unknown-linux-gnu:
    uses: ./.github/workflows/build.yaml
    with:
      runs_on: ubuntu-latest
      target: x86_64-unknown-linux-gnu

  x86_64-pc-windows-gnu:
    uses: ./.github/workflows/build.yaml
    with:
      runs_on: windows-2019
      target: x86_64-pc-windows-gnu
