name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  github_build:
    name: Build release binaries
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            binary: tgbr
            extension: tar.xz
          - target: x86_64-pc-windows-gnu
            os: windows-latest
            binary: tgbr.exe
            extension: zip

    runs-on: ${{ matrix.os }}
    steps:
      - name: Build | Install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install -y libasound2-dev libudev-dev libgtk-3-dev libxcb-shape0-dev libxcb-xfixes0-dev
      
      - name: Build | Checkout
        uses: actions/checkout@v2

      - name: Build | Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: ${{ matrix.target }}
          override: true

      - name: Build | rust-cache
        uses: Swatinem/rust-cache@v1

      - name: Build | Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=${{ matrix.target }}

      - name: Post Build | Prepare artifacts
        run: |
          strip target/${{ matrix.target }}/release/${{ matrix.binary }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: tgbr-${{ github.ref_name }}-${{ matrix.target}}.${{ matrix.extension }}
          path: target/${{ matrix.target }}/release/${{ matrix.binary }}
